apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balance-checker
  namespace: ninemm-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: holders.9mm.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: balance-checker
                port:
                  number: 80

