apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balance-checker
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - holders.9mm.pro
      secretName: balance-checker-tls
  rules:
    - host: holders.9mm.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: balance-checker
                port:
                  number: 80

